### ISSUE TITLE
Custom allocator support

### ISSUE THREAD

**Issue by sherief** [df308/x9#5]
I'm interested in integrating x9 in a project with soft real time constraints, and am also interested in tracking its memory use. Is custom allocator support something you have planned or are interested in implementing? If not, would you be open to merging PRs offering it? Any pointers / constraints that could affect this feature?

**Comment by df308** [comment]
Hi!

I have considered the idea of allowing users to use their own custom allocator but because of wanting to keep the definition of the x9_inbox private ended up deciding not to.

Regarding tracking memory use: there are no realloc calls inside X9, so perhaps you can track where you do the allocations?

If you can describe in more detail exactly what you would need, perhaps I can accomodate, since currently there are 24 bytes of padding in an x9_inbox that could be used.

I am currently working on a micro optimization update that should take me a few more days, so either way it would need to wait for after that, but give me some more information and I will see what I can do.

DF

**Comment by df308** [comment]
Closed because of no reply.

**Comment by sherief** [comment]
Twenty eight hours seems a bit low of a threshold to close for "no reply", especially when I and about a billion others were observing the religious holiday of Eid El Adha. 

You don't need to expose your struct layouts, just allow the user to pass a pointer to a stuct with a user-provided alloc and free functions to x9_create_*().

**Comment by df308** [comment]
Hi,

I consider the API stable so I can't accommodate what you are asking at the moment.
I do see the value in providing support for custom allocators but currently I am focusing on other aspects of the library. 
Are you sure you can't integrate X9 into your project as is? 

DF
